### ISSUE TITLE
Must initialize from damo-vilab/text-to-video-ms-1.7b?

### ISSUE THREAD

**Issue by Sutongtong233** [Picsart-AI-Research/StreamingT2V#17]
Hi, I found that here: 
https://github.com/Picsart-AI-Research/StreamingT2V/blame/c1b8068bcbcdbbfa0dd0df3371d3c93a1f5132de/t2v_enhanced/model_init.py#L71C7-L71C7

```
def init_streamingt2v_model(ckpt_file, result_fol):
       ...
      cli = CustomCLI(VideoLDM)
```
It seems that VideoLDM must initialized from damo-vilab/text-to-video-ms-1.7b (in config pipeline_repo: damo-vilab/text-to-video-ms-1.7b). Moreover, ckpt_file, which is the path to Stream_t2v.ckpt, just add to sys.argv, but not used in any function.
I am confused about this piece of code and hope to get your explanation, thanks :)

**Comment by hpoghos** [comment]
Hi @Sutongtong233,
The streamingt2v model is loaded at [line 105](https://github.com/Picsart-AI-Research/StreamingT2V/blame/c1b8068bcbcdbbfa0dd0df3371d3c93a1f5132de/t2v_enhanced/model_init.py#L105), 
you can check that it indeed uses the `streaming_t2v.ckpt`

**Comment by hben35096** [comment]
`python gradio_demo.py`

Even with V100-32GB, I still get:

```
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
PIPE LOADING DONE
CUSTOM XFORMERS ATTENTION USED.
Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/root/autodl-tmp/StreamingT2V/t2v_enhanced/gradio_demo.py", line 48, in <module>
    stream_cli, stream_model = init_streamingt2v_model(ckpt_file_streaming_t2v, result_fol)
  File "/root/autodl-tmp/StreamingT2V/t2v_enhanced/model_init.py", line 105, in init_streamingt2v_model
    model.load_state_dict(torch.load(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 81, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 31.74 GiB total capacity; 30.73 GiB already allocated; 60.88 MiB free; 31.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by zeroCAY** [comment]
I also have the question, I have the streaming_t2v.ckpt actually, but it still ask to download /laion/CLIP-ViT-H-14-laion2B-s32B-b79K from huggingface.
Because my server can't connect to huggingface for direct download, is this download behavior necessary? Is it possible to run the whole process with just streaming_t2v.ckpt ?
![image](https://github.com/Picsart-AI-Research/StreamingT2V/assets/26081609/2d73bcf3-3b56-4448-9102-d30bcfc288e6)

**Comment by Mike001-wq** [comment]
> I also have the question, I have the streaming_t2v.ckpt actually, but it still ask to download /laion/CLIP-ViT-H-14-laion2B-s32B-b79K from huggingface. Because my server can't connect to huggingface for direct download, is this download behavior necessary? Is it possible to run the whole process with just streaming_t2v.ckpt ? ![image](https://private-user-images.githubusercontent.com/26081609/321074940-2d73bcf3-3b56-4448-9102-d30bcfc288e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjMyOTgsIm5iZiI6MTcxMjcyMjk5OCwicGF0aCI6Ii8yNjA4MTYwOS8zMjEwNzQ5NDAtMmQ3M2JjZjMtM2I1Ni00NDQ4LTkxMDItZDMwYmNmYzI4OGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA0MjMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZDI3ODM0MGJlMDFhYzQ0MWYzNTNhOGJkNjU5NzY2MGRjZGRmNjBlNTA3M2M3Y2IwMWEwODEwOTNhYjliZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMW1DEfPhogsFe1alErEqQRTmXaSS4T85pe-NpSOhvM)

I solve this problem by change image_embedder.py Line 75:
        model, _, _ = open_clip.create_model_and_transforms(
            arch,
            device=torch.device("cpu"),
            # pretrained=version,
            pretrained="./damo-vilab/open_clip_pytorch_model.bin"
        )

**Comment by zeroCAY** [comment]
> > I also have the question, I have the streaming_t2v.ckpt actually, but it still ask to download /laion/CLIP-ViT-H-14-laion2B-s32B-b79K from huggingface. Because my server can't connect to huggingface for direct download, is this download behavior necessary? Is it possible to run the whole process with just streaming_t2v.ckpt ? ![image](https://private-user-images.githubusercontent.com/26081609/321074940-2d73bcf3-3b56-4448-9102-d30bcfc288e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjMyOTgsIm5iZiI6MTcxMjcyMjk5OCwicGF0aCI6Ii8yNjA4MTYwOS8zMjEwNzQ5NDAtMmQ3M2JjZjMtM2I1Ni00NDQ4LTkxMDItZDMwYmNmYzI4OGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA0MjMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZDI3ODM0MGJlMDFhYzQ0MWYzNTNhOGJkNjU5NzY2MGRjZGRmNjBlNTA3M2M3Y2IwMWEwODEwOTNhYjliZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMW1DEfPhogsFe1alErEqQRTmXaSS4T85pe-NpSOhvM)
> 
> I solve this problem by change image_embedder.py Line 75: model, _, _ = open_clip.create_model_and_transforms( arch, device=torch.device("cpu"), # pretrained=version, pretrained="./damo-vilab/open_clip_pytorch_model.bin" ) pretrained parameter points to your file's path, which is downloaded from huggingface.

thanks，I solve the problem by using your method~

**Comment by kunkun-zhu** [comment]
Hi   @Sutongtong233 ，
Have you solved the problem？
I also have the question。“OSError: Cannot load model damo-vilab/text-to-video-ms-1.7b: model is not cached locally”，but I can't connect to huggingface.

**Comment by ffhelly** [comment]
> 嗨，你解决了问题吗？ 我也有问题。“OSError：无法加载模型 damo-vilab/text-to-video-ms-1.7b：模型未缓存本地”，但我无法连接到 huggingface。

从镜像站拉一份到本地。或者开科技下载

**Comment by theoldsong** [comment]
> > 嗨，你解决了问题吗？ 我也有问题。“OSError：无法加载模型 damo-vilab/text-to-video-ms-1.7b：模型未缓存本地”，但我无法连接到 huggingface。
> 
> 从镜像站拉一份到本地。或者开科技下载

请问damo-vilab/text-to-video-ms-1.7b存放路径在哪，为什么我下载了，一直提示未找到路径

**Comment by Mike001-wq** [comment]
> > > 嗨，你解决了问题吗？ 我也有问题。“OSError：无法加载模型 damo-vilab/text-to-video-ms-1.7b：模型未缓存本地”，但我无法连接到 huggingface。
> > 
> > 
> > 从镜像站拉一份到本地。或者开科技下载
> 
> 请问damo-vilab/text-to-video-ms-1.7b存放路径在哪，为什么我下载了，一直提示未找到路径

你指定存放路径，或者在当前工作路径下应该有一个叫damo-vilab的文件夹

**Comment by theoldsong** [comment]
> > > > 嗨，你解决了问题吗？ 我也有问题。“OSError：无法加载模型 damo-vilab/text-to-video-ms-1.7b：模型未缓存本地”，但我无法连接到 huggingface。
> > > 
> > > 
> > > 从镜像站拉一份到本地。或者开科技下载
> > 
> > 
> > 请问damo-vilab/text-to-video-ms-1.7b存放路径在哪，为什么我下载了，一直提示未找到路径
> 
> 你指定存放路径，或者在当前工作路径下应该有一个叫damo-vilab的文件夹

都试过了，一直提示找不到路径。。。

**Comment by Mike001-wq** [comment]
> > > > > 嗨，你解决了问题吗？ 我也有问题。“OSError：无法加载模型 damo-vilab/text-to-video-ms-1.7b：模型未缓存本地”，但我无法连接到 huggingface。
> > > > 
> > > > 
> > > > 从镜像站拉一份到本地。或者开科技下载
> > > 
> > > 
> > > 请问damo-vilab/text-to-video-ms-1.7b存放路径在哪，为什么我下载了，一直提示未找到路径
> > 
> > 
> > 你指定存放路径，或者在当前工作路径下应该有一个叫damo-vilab的文件夹
> 
> 都试过了，一直提示找不到路径。。。

用绝对路径试试？
