### ISSUE TITLE
No module named 't2v_enhanced'

### ISSUE THREAD

**Issue by Yuehongzhe** [Picsart-AI-Research/StreamingT2V#35]
![1713790476091](https://github.com/Picsart-AI-Research/StreamingT2V/assets/150451257/05393c1c-fed0-430c-bddb-0b229afbfe6e)

(.venv) PS D:\Python file\StreamingT2V-main\StreamingT2V-main\t2v_enhanced>  python inference.py --prompt="A cat running on the street"
Traceback (most recent call last):
  File "D:\Python file\StreamingT2V-main\StreamingT2V-main\t2v_enhanced\inference.py", line 11, in <module>
    from t2v_enhanced.model.video_ldm import VideoLDM
ModuleNotFoundError: No module named 't2v_enhanced'

**Comment by xinsonggaodragonplus** [comment]
you can add this in gradio_demo.py and inference.py

import sys
sys.path.append("../")
sys.path.append("../t2v_enhanced/")
![image](https://github.com/Picsart-AI-Research/StreamingT2V/assets/165622067/d662374e-0463-4cd7-bd3d-b0a9a66ab3ea)

**Comment by lindadev77** [comment]
I meet this problem also.

**Comment by iopa788** [comment]
D:\StreamingT2V\StreamingT2V\StreamingT2V\t2v_enhanced>python inference.py --prompt="A cat running on the street"
Traceback (most recent call last):
  File "D:\StreamingT2V\StreamingT2V\StreamingT2V\t2v_enhanced\inference.py", line 11, in <module>
    from t2v_enhanced.model.video_ldm import VideoLDM
ModuleNotFoundError: No module named 't2v_enhanced'

**Comment by susuna1640** [comment]
I had the same problem. However, I did this by setting the PYTHONPATH environment variables, like this `export PYTHONPATH=/home/StreamingT2V:$PYTHONPATH`.
