### ISSUE TITLE
Failed to load CLIP from local

### ISSUE THREAD

**Issue by leonardodora** [Picsart-AI-Research/StreamingT2V#7]
I want to use the downloaded clip model, so I change the 'pretrained' to the model path. like this:
 model, _, _ = open_clip.create_model_and_transforms(
            arch,
            pretrained='/root/.cache/huggingface/hub/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin',
            device=torch.device("cpu"),
            #pretrained=version,
        )
But it occurs the error：

Traceback (most recent call last):
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/jsonargparse/typehints.py", line 785, in adapt_typehints
    val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/jsonargparse/typehints.py", line 996, in adapt_class_type
    return val_class(**{**init_args, **dict_kwargs})
  File "/root/proj/StreamingT2V/t2v_enhanced/model/diffusers_conditional/models/controlnet/image_embedder.py", line 75, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/open_clip/factory.py", line 387, in create_model_and_transforms
    model = create_model(
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/open_clip/factory.py", line 291, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/open_clip/factory.py", line 160, in load_checkpoint
    resize_text_pos_embed(state_dict, model)
  File "/root/miniconda3/envs/st2v/lib/python3.10/site-packages/open_clip/model.py", line 573, in resize_text_pos_embed
    assert old_width == width, 'text pos_embed width changed!'
AssertionError: text pos_embed width changed!

Do I have another way to load the clip model locally？

**Comment by hpoghos** [comment]
I would sugest just to use the `open_clip` weights,
if that's not an option you can swap the `open_clip` model initialization
with something like this `CLIPVisionModelWithProjection.from_pretrained("laion/CLIP-ViT-H-14-laion2B-s32B-b79K")`
and use your local weights, you also need to make the apropriate changes in `encode_with_vision_transformer`
